version: "3"

services:
  hasher:
    image: dockercoins_hasher
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  redis:
    image: redis
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  rng:
    image: dockercoins_rng
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  webui:
    image: dockercoins_webui
    ports:
      - "8000:80"
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  worker:
    image: dockercoins_worker
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

networks:
  coinswarmnet:
    external: true
