version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - loggingnet
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.17.9
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - loggingnet

  logstash:
    image: logstash:7.17.9
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      mode: global
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logstash-pipeline:/usr/share/logstash/pipeline/
    networks:
      - loggingnet
      - coinswarmnet

configs:
  logstash_config:
    file: ./logstash.conf

volumes:
  esdata:
    driver: local
  logstash-pipeline:
    driver: local

networks:
  loggingnet:
    external: true
  coinswarmnet:
    external: true