version: '3.8'

services:
  # Dịch Vụ Dockercoins
  rng:
    image: vietphuong1008/dockercoins_rng:latest
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  hasher:
    image: vietphuong1008/dockercoins_hasher:latest
    ports:
      - "8002:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  worker:
    image: vietphuong1008/dockercoins_worker:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  webui:
    image: vietphuong1008/dockercoins_webui:latest
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - coinswarmnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # Dịch Vụ ELK Stack
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - coinswarmnet
    ports:
      - "12201:12201/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - coinswarmnet
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - coinswarmnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  coinswarmnet:
    external: true
