version: "3"

services:
  rng:
    image: dockercoins_rng:latest
    networks:
      - coinswarmnet

  hasher:
    image: dockercoins_hasher:latest
    networks:
      - coinswarmnet

  webui:
    image: dockercoins_webui:latest
    ports:
      - "8000:80"
    networks:
      - coinswarmnet

  redis:
    image: redis
    networks:
      - coinswarmnet

  worker:
    image: dockercoins_worker:latest
    networks:
      - coinswarmnet

networks:
  coinswarmnet:
    external: true