version: "3"

services:
  rng:
    build: rng
    ports:
    - "8001:80"
    container_name: rng
    networks:
      - loggingnet

  hasher:
    build: hasher
    ports:
    - "8002:80"
    container_name: hasher
    networks:
      - loggingnet

  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    container_name: webui
    networks:
      - loggingnet

  redis:
    image: redis
    container_name: redis
    networks:
      - loggingnet

  worker:
    build: worker
    networks:
      - loggingnet

networks:
  loggingnet:
    driver: overlay