version: "3"

services:
  hasher:
     image: vietphuong1008/dockercoins_hasher:latest
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  redis:
    image: redis
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  rng:
    image: vietphuong1008/dockercoins_rng:latest
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  webui:
     image: vietphuong1008/dockercoins_webui:latest
    ports:
      - "8000:80"
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

  worker:
    image: vietphuong1008/dockercoins_worker:latest
    networks:
      - coinswarmnet
    depends_on:
      - redis
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash.loggingnet:12201"

networks:
  coinswarmnet:
    external: true
