version: '3.8'

services:
  # Dịch Vụ Dockercoins
  rng:
    image: vietphuong1008/dockercoins_rng:latest
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  hasher:
    image: vietphuong1008/dockercoins_hasher:latest
    ports:
      - "8002:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  worker:
    image: vietphuong1008/dockercoins_worker:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  webui:
    image: vietphuong1008/dockercoins_webui:latest
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - coinswarmnet
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://logstash:12201"

  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - coinswarmnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  coinswarmnet:
    external: true
